### ISSUE TITLE
Have an Installation section

### ISSUE THREAD

**Issue by pocc** [Lucas-C/pre-commit-hooks-markup#2]
I'm assuming that you need to `pip install restructuredtext_lint` first? What versions of Python are compatible?

**Comment by Lucas-C** [comment]
Thanks for your interest.
Do you know this repo main purpose is to be used through the [pre-commit](https://pre-commit.com) command ?

The information you are requesting is already present in the `.travis.yml` :
https://github.com/Lucas-C/pre-commit-hooks-markup/blob/master/.travis.yml

The unit tests are executed as part as the `pre-commit` hooks configured by this file :
https://github.com/Lucas-C/pre-commit-hooks-markup/blob/master/.pre-commit-config.yaml#L21

Feel free to send a PR if you want to improve the README though.
I'm closing this issue for now, as this is no bug nor feature request.
