### ISSUE TITLE
Please replace git:// by https:// in the readme for user security

### ISSUE THREAD

**Issue by hartwork** [Lucas-C/pre-commit-hooks-markup#5]
Hi!

Nice hook — thanks for it!
Only after applying the snippet you recommended in https://github.com/Lucas-C/pre-commit-hooks-markup/blame/master/README.md#L8 my eyes caught the `git://` which is vulnerable to man-in-the-middle attacks. Would you mind recommending `https://` for a safe default, instead?

Thanks and best, Sebastian

**Comment by Lucas-C** [comment]
Thanks for reporting this.
Done !

**Comment by hartwork** [comment]
Thank you!
